version: 2
jobs:
  build:
    docker:
      - image: brandembassy/php:7.2-fpm-noxdebug
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.lock" }}

      - run: composer test
      - run: composer phpcs
      - run: composer phpstan
